
#Dedault configuration
spring:
  profiles:
    active: dev

#MapperLocations /src/main/resources
mybatis:
  typeAliasesPackage: com.anxin.education.entity
  mapperLocations: classpath:mapping/*.xml


---

#Development configuration
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/lab3?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql2018
    driver-class-name: com.mysql.cj.jdbc.Driver

    # use druid Datasource
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false

server:
  port: 8080

